package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"fmt"
	"github.com/mitchellh/mapstructure"

	"github.com/kevinmichaelchen/go-gqlgen-schemaless-example/internal/handler/graphql/generated"
	"github.com/kevinmichaelchen/go-gqlgen-schemaless-example/internal/handler/model"
	"github.com/sanity-io/litter"
)

// CreateFoo is the resolver for the createFoo field.
func (r *mutationResolver) CreateFoo(ctx context.Context, input model.CreateFooInput) (*model.Foo, error) {
	var result model.Attributes
	err := mapstructure.Decode(input.Attributes, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal attributes: %w", err)
	}

	litter.Dump(result)
	return &model.Foo{Name: "foo"}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
