// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kevinmichaelchen/go-gqlgen-schemaless-example/internal/handler/model/custom"
)

type CreateFooInput struct {
	NestedObject custom.JSON `json:"nestedObject"`
}

type Foo struct {
	Name string `json:"name"`
}
